### PR TITLE
TEST-180 was updated

### PR DESCRIPTION
**Pull request by vfedrunov**
[video](https://www.dropbox.com/s/9jbh2q9uo1lp4if/issue-167.mp4?dl=0)

### CODE REVIEW

**Review by asloman — COMMENTED** [review]
2021-01-05_08h56_36

All looks good. Is there a way to tidy up the logs? Rather than have this message repeated 9 times.

**Comment by asloman** [comment]
As discussed, it would be better to modify the logs so instead it looked like:
"The result list shows required files with the filter: Docx displayed on page (8/8)"

**Comment by vfedrunov** [comment]
> As discussed, it would be better to modify the logs so instead it looked like:
> "The result list shows required files with the filter: Docx displayed on page (8/8)"

Done
image

**Review by asloman — APPROVED** [review]
All looks good to me!

**Review by NadHodeGW — APPROVED** [review]

**Pull request merged**
