### PR TITLE
Issue #162, issue #174, issue 175

### PR DESCRIPTION
**Pull request by vfedrunov**
Updated steps for TEST-121 (issue#162)
Added steps for TEST-242 (issue#174), TEST-243 (issue#175)

### CODE REVIEW

**Comment by vfedrunov** [comment]
@NadHodeGW , @asloman , please, observe the [video with tests run](https://www.dropbox.com/s/5ug70cwstmxd19d/issue-162-1.mp4?dl=0)

**Comment by asloman** [comment]
Thing I notice on the video, the second part where it sends the video should be checking if the file was disallowed (that is currently a known issue). So the file should be returning as blocked, and therefore would fail the test.

The line should look like this.
2021-01-13_15h16_46

**Comment by vfedrunov** [comment]
> Thing I notice on the video, the second part where it sends the video should be checking if the file was disallowed (that is currently a known issue). So the file should be returning as blocked, and therefore would fail the test.
> 
> The line should look like this.
> 2021-01-13_15h16_46

Thank you for review!
My last commit broke the test. I will revert this changes

**Comment by vfedrunov** [comment]
> Thing I notice on the video, the second part where it sends the video should be checking if the file was disallowed (that is currently a known issue). So the file should be returning as blocked, and therefore would fail the test.
> 
> The line should look like this.
> 2021-01-13_15h16_46

@asloman done
https://github.com/filetrust/icap-management-ui-tests/pull/176/commits/4fc8e29bf026262dd1cf454d122ce4ad38b9c7f5

**Review by NadHodeGW — CHANGES_REQUESTED** [review]
File processing still doesn't work
image
Check function: createFile which is causing a typeError

**Review by NadHodeGW — APPROVED** [review]
Merging to get in the fix for publish policy, please fix test 212 in next PR

**Pull request merged**
